services:
  mongodb:
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=u9678521
      - MONGO_INITDB_ROOT_PASSWORD=p6845976
    restart: unless-stopped

volumes:
  mongodb_data: